---
# See: https://wiki.gentoo.org/wiki/Profile_(Portage)

- name: Check whether we've chosen our Portage profile yet
  ansible.builtin.stat:
    path: /tmp/profile_chosen
  register: profile_chosen

- name: Select our Portage profile with eselect
  ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile set {{ eselect_profile }}'
  when:
    - not profile_chosen.stat.exists

- name: Update environment with env-update (new eselect profile)
  ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; env-update'
  when:
    - not profile_chosen.stat.exists

- name: Write state file to show this task has completed
  ansible.builtin.file:
    path: /tmp/profile_chosen
    state: touch
    owner: root
    group: root
    mode: '0644'
  when:
    - not profile_chosen.stat.exists
...
