---
- name: Set timezone
  command: chroot /mnt/gentoo bash -c 'cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime; echo "{{ timezone }}" > /etc/timezone'

- name: Configure /etc/hosts
  template:
    src: hosts
    dest: /mnt/gentoo/etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Configure /etc/fstab
  template:
    src: fstab
    dest: /mnt/gentoo/etc/fstab
    owner: root
    group: root
    mode: '0644'

- name: Create /etc/portage/make.conf (idempotent, runs even if we've run this role before)
  template:
    src: make.conf
    dest: /mnt/gentoo/etc/portage/make.conf
    owner: root
    group: root
    mode: '0644'

- name: Create /etc/portage/package.use (idempotent, runs even if we've run this role before)
  copy:
    src: package.use
    dest: /mnt/gentoo/etc/portage/package.use
    owner: root
    group: root
    mode: '0644'

- name: Copy locale.gen over to configure the supported locales for the system
  copy:
    src: locale.gen
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: '0644'

- name: Configure locales
  command: chroot /mnt/gentoo bash -c 'locale-gen'

- name: Set locale
  copy:
    src: 02locale
    dest: /etc/env.d/02locale
    owner: root
    group: root
    mode: '0644'

- name: Update environment with env-update (idempotent, runs even if we've run this role before)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; env-update'
...
