---
# stage3 & base system installation
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Stage
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base

- name: Check the remote host to see whether we've already completed the stage3 step
  stat:
    path: /tmp/stage3_completed
  register: stage3_completed

- name: Copy Over Stage Retrieval Script
  template:
    src: get_stage.sh
    dest: /mnt/gentoo/
    owner: root
    group: root
    mode: '0755'
  when:
    - not stage3_completed.stat.exists

- name: Download Stage3 Tarball
  command: /mnt/gentoo/get_stage.sh chdir=/mnt/gentoo
  when:
    - not stage3_completed.stat.exists

- name: Unarchive Stage3 Tarball
  unarchive:
    src: /mnt/gentoo/stage3.tar.bz2
    dest: /mnt/gentoo/
    remote_src: true
  when:
    - not stage3_completed.stat.exists

# We run the /proc /dev/ and /sys bind mount commands whether or not
# we have already run this playbook role. Without making sure the relevant
# system dirs are mounted into the chroot we can't do stuff like grub-mkconfig
# and other things that rely on /dev and similar system dirs.
- name: proc bind mounts
  command: mount -t proc proc /mnt/gentoo/proc
  args:
    creates: /mnt/gentoo/proc/zoneinfo
    warn: false
  tags:
  - skip_ansible_lint

- name: dev bind mounts
  command: mount --rbind /dev /mnt/gentoo/dev
  args:
    creates: /mnt/gentoo/dev/zero
    warn: false
  tags:
  - skip_ansible_lint

- name: sys bind mounts
  command: mount --rbind /sys /mnt/gentoo/sys
  args:
    creates: /mnt/gentoo/sys/dev
    warn: false
  tags:
  - skip_ansible_lint

- name: Cleanup Stage3 Archive
  file:
    path: /mnt/gentoo/stage3.tar.bz2
    state: absent
  when:
    - not stage3_completed.stat.exists

- name: Cleanup get_stage.sh
  file:
    path: /mnt/gentoo/get_stage.sh
    state: absent
  when:
    - not stage3_completed.stat.exists

- name: copy resolv.conf
  command: cp -L /etc/resolv.conf /mnt/gentoo/etc/ creates=/mnt/gentoo/etc/resolv.conf
  when:
    - not stage3_completed.stat.exists

- name: create portage directory
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; mkdir /usr/portage' creates=/mnt/gentoo/usr/portage
  when:
    - not stage3_completed.stat.exists

- name: Install ebuild repo snapshot
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; /usr/bin/emerge-webrsync' creates=/mnt/gentoo/usr/portage/xfce-extra
  when:
    - not stage3_completed.stat.exists

# This shouldn't really be necessary as per the Gentoo Handbook, but 'eselect profile list' was just showing
# up no profiles at all without it.
- name: Update ebuild repo
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; /usr/bin/emerge --sync'
  when:
    - not stage3_completed.stat.exists

- name: Write state file to show this task has completed
  file:
    path: /tmp/stage3_completed
    state: touch
    owner: root
    group: root
    mode: '0644'
  when:
    - not stage3_completed.stat.exists
...
