---
- name: Check the remote host to see whether we've already configured the filesystems
  ansible.builtin.stat:
    path: /tmp/filesystems_completed
  register: filesystems_completed

- name: Format /boot Partition
  community.general.filesystem:
    fstype: "vfat"
    dev: "{{ boot_partition }}"
    force: "{{ force_format }}"
    opts: "-F 32"
  when:
    - not filesystems_completed.stat.exists

- name: Create main LVM group
  community.general.lvg:
    pvs: "{{ root_partition }}"
    vg: "{{ vg_name }}"
  when:
    - not filesystems_completed.stat.exists

- name: Create swap volume
  community.general.lvol:
    lv: swap
    vg: "{{ vg_name }}"
    size: "{{ swap_size }}"
  when:
    - not filesystems_completed.stat.exists

- name: Format swap volume
  ansible.builtin.command: "mkswap /dev/mapper/{{ vg_name }}-swap"
  when:
    - not filesystems_completed.stat.exists

# This seems to be pretty critical as when I just had 4GB RAM I had some big builds like Spidermonkey
# error out due to what appeared to be an OOM error:
# https://stackoverflow.com/questions/37128813/installing-lxml-error-open-cfi-at-the-end-of-file-missing-cfi-endproc-direct
- name: Enable swap now (it will help us build big things later!)
  ansible.builtin.command: "swapon /dev/mapper/{{ vg_name }}-swap"
  when:
    - not filesystems_completed.stat.exists

- name: Create root lvm volume group
  community.general.lvol:
    lv: root
    vg: "{{ vg_name }}"
    size: "{{ root_size }}"
    shrink: false
  when:
    - not filesystems_completed.stat.exists

- name: Format root volume
  community.general.filesystem:
    fstype: "{{ mainfstype }}"
    dev: "/dev/mapper/{{ vg_name }}-root"
    force: "{{ force_format }}"
  when:
    - not filesystems_completed.stat.exists

- name: Create mountpoints
  ansible.builtin.file:
    path: /mnt/gentoo/boot
    state: directory
  when:
    - not filesystems_completed.stat.exists

- name: Mount /
  ansible.posix.mount:
    path: /mnt/gentoo
    src: /dev/mapper/{{ vg_name }}-root
    fstab: /tmp/tmp_fstab
    fstype: "{{ mainfstype }}"
    state: mounted
  when:
    - not filesystems_completed.stat.exists

- name: Mount /boot
  ansible.posix.mount:
    path: /mnt/gentoo/boot
    src: "{{ boot_partition }}"
    fstab: /tmp/tmp_fstab
    fstype: "vfat"
    state: mounted
  when:
    - not filesystems_completed.stat.exists

- name: Write state file to show this task has completed
  ansible.builtin.file:
    path: /tmp/filesystems_completed
    state: touch
    owner: root
    group: root
    mode: '0644'
  when:
    - not filesystems_completed.stat.exists
...
