---
- name: Install useful system packages (will run on the fully logged in system now, no chroot)
  portage:
    package: '{{ item }}'
  with_items:
    - app-admin/sudo
    - app-misc/tmux
    - dev-python/pip
    - dev-vcs/git
    - sys-process/below
    - sys-process/htop
  tags:
    - postinstall
...
