---
# For some reason the python2.7 emerge (dependency of something else) breaks if we don't remount /dev before emerging it
# See: https://forums.gentoo.org/viewtopic-t-982100-start-0.html
- name: Remount /dev to get /dev/mapper visible (otherwise emerging python2.7 breaks)
  command: mount --rbind /dev /mnt/gentoo/dev
  args:
    warn: false
  tags:
    - skip_ansible_lint

- name: Emerge app-admin/syslog-ng (for logging)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge app-admin/syslog-ng'
  args:
    creates: /mnt/gentoo/usr/sbin/syslog-ng

- name: Enable syslog-ng systemd service
  command: chroot /mnt/gentoo bash -c 'systemctl enable syslog-ng@default'

- name: Emerge sys-process/cronie (for scheduling with cron)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge sys-process/cronie'
  args:
    creates: /mnt/gentoo/etc/init.d/cronie

- name: Enable cronie systemd service
  command: chroot /mnt/gentoo bash -c 'systemctl enable cronie'

- name: Emerge sys-boot/grub (The --deep flag is recommended on this page https://wiki.gentoo.org/wiki/GRUB2#Emerge)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge --deep sys-boot/grub'
  args:
    creates: /mnt/gentoo/usr/sbin/grub-install

- name: Emerge app-portage/gentoolkit (required to use the Portage module for Ansible when we're booted into the system)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge app-portage/gentoolkit'
  args:
    creates: /mnt/gentoo/usr/bin/equery
...
