---
# Configure passwords
root_password: "root-password"
unprivileged_user: user
unprivileged_user_password: "user-password"

# Configure Ansible connection options
ansible_become_pass: "{{ root_password }}"
ansible_pass: "{{ root_password }}"
ansible_ssh_pass: "{{ root_password }}"

# Configure our boot firmware type (acceptable values for firmware_type are 'bios' or 'efi')
firmware_type: 'bios'

# Configure installed system options
gentoo_hostname: gentoo
timezone: Europe/London

# Configure our package mirror
mirror: "{{ mirror_baseurl | default('https://www.mirrorservice.org')}}/sites/distfiles.gentoo.org"

# Configure networking
domain: localdomain
management_interface: "{{ ansible_default_ipv4.interface }}"
gateway: "{{ ansible_default_ipv4.gateway }}"
netmask: "{{ ansible_default_ipv4.netmask }}"

# Configure disk layout
# Note: If testing in libvirt/QEMU then be aware that the main disk will turn up as /dev/vda
force_format: true
main_disk: /dev/sda
mainfstype: xfs  # Using XFS since EXT4 seemed to suffer inode exhaustion during 'emerge --sync'
root_size: 95%FREE
swap_size: 4096m
vg_name: '{{ gentoo_hostname }}'

# Auto-calculate boot and root partition offsets
boot_id: "{{ '2' if firmware_type == 'bios' else '1' }}"
root_id: "{{ '3' if firmware_type == 'bios' else '2' }}"
boot_partition: '{{ main_disk }}{{ boot_id }}'
root_partition: '{{ main_disk }}{{ root_id }}'

# Configure eselect profile here
eselect_profile: 'default/linux/amd64/17.1/desktop/gnome/systemd'
...
