---
- name: Show kernel version (pre-update)
  ansible.builtin.command: uname -a
  register: kernelpre
  changed_when: false

- name: Print kernel version
  ansible.builtin.debug: msg="{{ kernelpre.stdout }}"

# Note (Dec 2024) - it looks like Gentoo no longer ships ntpd in the LiveCD
#                   so this might be a problem that recurs. Will need to find
#                   a fix.
#
# - name: Check time
#   ansible.builtin.command: date
#   register: datepre
#   changed_when: false
# 
# - name: Display time before sync
#   ansible.builtin.debug: msg="{{ datepre.stdout }}"
# 
# - name: Run NTP sync (in case we have restored a VM snapshot and the clock is wrong)
#   ansible.builtin.command: ntpd -q -g
#   changed_when: false
#   when: ansible_virtualization_role == "guest"
# 
# - name: Check time again
#   ansible.builtin.command: date
#   register: datepost
#   changed_when: false
# 
# - name: Display time now
#   ansible.builtin.debug: msg="{{ datepost.stdout }}"
...
