---
- name: Show kernel version (pre-update)
  command: uname -a
  register: kernelpre
  changed_when: false

- name: Print kernel version
  debug: msg="{{ kernelpre.stdout }}"

- name: Check time
  command: date
  register: datepre
  changed_when: false

- name: Display time before sync
  debug: msg="{{ datepre.stdout }}"

- name: Run NTP sync (in case we have restored a VM snapshot and the clock is wrong)
  command: ntpd -q -g
  changed_when: false
  when: ansible_virtualization_role == "guest"

- name: Check time again
  command: date
  register: datepost
  changed_when: false

- name: Display time now
  debug: msg="{{ datepost.stdout }}"
...
