---
- name: Install dbus
  community.general.portage:
    package: sys-apps/dbus
  tags:
    - desktop

- name: Install GNOME
  community.general.portage:
    package: gnome-base/gnome-light
  tags:
    - desktop

- name: Enable dbus
  ansible.builtin.service:
    name: dbus.service
    enabled: true
  tags:
    - desktop

- name: Enable GDM
  ansible.builtin.service:
    name: gdm.service
    enabled: true
  tags:
    - desktop
...
