---
- name: Install Docker
  community.general.portage:
    package: '{{ item }}'
  with_items:
    - app-emulation/docker
    - dev-python/docker-py
  tags:
    - postinstall

- name: Start & enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  tags:
    - postinstall
...
