---
- name: Install Docker
  portage:
    package: '{{ item }}'
  with_items:
    - app-emulation/docker
    - dev-python/docker-py
  tags:
    - postinstall

- name: Start & enable Docker service
  service:
    name: docker
    enabled: true
    state: started
  tags:
    - postinstall
...
