---
- name: Copy package.use
  copy:
    src: package.use
    dest: /etc/portage/package.use
    owner: root
    group: root
    mode: '0644'
  tags:
    - postinstall

- name: Copy package.accept_keywords
  copy:
    src: package.accept_keywords
    dest: /etc/portage/package.accept_keywords
    owner: root
    group: root
    mode: '0644'
  tags:
    - postinstall

- name: Copy make.conf
  template:
    src: make.conf
    dest: /etc/portage/make.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - postinstall

- name: Enable systemd-timesyncd for NTP
  service:
    name: systemd-timesyncd
    enabled: true
  tags:
    - postinstall

- name: Set hostname
  command: hostnamectl set-hostname {{ gentoo_hostname }}
  tags:
    - desktop

- name: Allow wheel group sudo access (validates sudoers file before saving)
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel ALL='
    line: '%wheel ALL=(ALL) ALL'
    validate: /usr/sbin/visudo -cf %s
  tags:
    - postinstall
...
