---
- name: Copy package.use
  copy:
    src: package.use
    dest: /etc/portage/package.use
    owner: root
    group: root
    mode: '0644'
  tags:
    - postinstall

- name: Copy make.conf
  template:
    src: make.conf
    dest: /etc/portage/make.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - postinstall

- name: Enable systemd-timesyncd for NTP
  service:
    name: systemd-timesyncd
    enabled: true
  tags:
    - postinstall

- name: Set hostname
  command: hostnamectl set-hostname {{ gentoo_hostname }}
  tags:
    - desktop
...
